[project]
name = "aichaoxys-blog"
version = "0.1.0"
description = ""
authors = [
    {name = "aichaoxy", email = "hadoop90@gmail.com"},
]
dependencies = [
    "pelican[markdown]>=4.9.1",
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

